---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: exabgp_exporter
    binary: exabgp_exporter
    main: ./cmd/exabgp_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - dragonfly
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    tags:
      - netgo
    ldflags:
      - >
          -s
          -w
          -X "github.com/prometheus/common/version.Version={{ .Version }}"
          -X "github.com/prometheus/common/version.Revision={{ .Commit }}"
          -X "github.com/prometheus/common/version.BuildDate={{ .Date }}"
          {{- if index .Env "GITHUB_REF_NAME" }}
          -X "github.com/prometheus/common/version.Branch={{ .Env.GITHUB_REF_NAME }}"
          {{- end }}
          {{- if index .Env "BUILD_USER" }}
          -X "github.com/prometheus/common/version.BuildUser={{ .Env.BUILD_USER }}"
          {{- end }}

checksum:
  name_template: "checksums.txt"
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
