version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/{{REPO_NAME}}
    steps:
      - checkout
      - run:
        name: coverage
        command: script/coverage
      - run:
        name: lint
        command: script/lint
      - run:
        name: test
        command: script/test
      - setup_remote_docker
      - run:
        name: build-test-container
        command: script/build-docker
      - run:
        name: run-test-container
        command: script/run-docker
      - run:
        name: stop-test-container
        command: script/stop-docker