version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: coverage
          command: script/coverage
      - run:
          name: lint
          command: script/lint
      - run:
          name: test
          command: script/test
  integration:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build-container
          command: script/build-docker
      - run:
          name: run-container
          command: script/run-docker
      - run:
          name: test
          command: script/test-docker
      - run:
          name: stop-container
          command: script/stop-docker