version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/{{REPO_NAME}}
    steps:
      - checkout
      - run: script/coverage
      - run: script/lint
      - run: script/test