#!/bin/bash
set -Eeuo pipefail
# shellcheck disable=SC1091
source script/env

build_args=()

if [ -n "${PYTHON_VERSION:-}" ]; then
    build_args+=("--build-arg PYTHON_VERSION=${PYTHON_VERSION}")
fi

docker build --rm ${build_args[@]} -t exabgp_exporter .
